### ISSUE TITLE
Number found where operator expected at {path}/warnings.pm line {line}, near "caller 1

### ISSUE THREAD

**Issue by elderling** [renormalist/data-dpath#14]
`Data::DPath::Context` isn't playing nice with `Test::Exception`.
## Perl 5.26.0

```
perl -MTest::Exception -MData::DPath::Context -e '1'
Number found where operator expected at /Users/jonathantaylor/perl5/perlbrew/perls/perl-5.26.0/lib/5.26.0/warnings.pm line 353, near "caller 1"
        (Do you need to predeclare caller?)
```

## Perl 5.16.3

```
perl -MTest::Exception -MData::DPath::Context -e '1'
Number found where operator expected at /Users/jonathantaylor/perl5/perlbrew/perls/perl-5.16.3/lib/5.16.3/warnings.pm line 444, near "caller 1"
        (Do you need to predeclare caller?)
```
Reversing the load order stops the warning from happening:

```
perl -MData::DPath::Context -MTest::Exception -e '1' # No warning
```

The behavior has something to do with how the `Safe` module is being used. Pull request forthcoming.

**Comment by renormalist** [comment]
Can you please verify that my just pushed version from github works for you?
If it does feel free to close this issue, otherwise I do on next cpan upload.

Thanks!

**Comment by elderling** [comment]
Verified! Thank you very much!

**Comment by renormalist** [comment]
Cool. So I just uploaded it as v0.57 to CPAN, let's see if CPANTESTERS also succeed.
Thanks for your report and verifying.
