### ISSUE TITLE
Explosion of NYTProf cruft

### ISSUE THREAD

**Issue by kentfredric** [renormalist/data-dpath#6]
https://cpan.metacpan.org/authors/id/S/SC/SCHWIGON/Data-DPath-0.51.tar.gz : 8.1MB
https://cpan.metacpan.org/authors/id/S/SC/SCHWIGON/Data-DPath-0.50.tar.gz : 266kb

https://metacpan.org/source/SCHWIGON/Data-DPath-0.51/nytprof # Loads of cruft
https://metacpan.org/source/SCHWIGON/Data-DPath-0.51/nytprof.out  # 7MB File

https://metacpan.org/diff/file?target=SCHWIGON/Data-DPath-0.51/&source=SCHWIGON/Data-DPath-0.50/   # Intrarelease diff that will choke your browser.

**Comment by renormalist** [comment]
Bummer! Thanks for reporting, will upload again. Sorry for late answer.

**Comment by renormalist** [comment]
I just uploaded a much smaller v0.52 to CPAN.
